name: cat_breeds_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  get_it: ^7.6.0
  injectable: ^2.3.0
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  bloc_test: ^10.0.0
  mockito: ^5.4.0
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env